name: Tests Unitarios - Jest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar Pruebas Lógicas (Jest)
        # Si un test falla, el pipeline se detiene inmediatamente
        run: npm test